version: 2
jobs:
 build:
  docker:
   - image: circleci/node:latest
  steps:
  - checkout
  - run: 
          command: |
            export $SURGE_DOMAIN=if [$CIRCLE_BRANCH=="master"] then "https://hgnapplication.surge.sh" else `https://hgnapplication_develop.surge.sh" fi
            echo $SURGE_DOMAIN
  - run:
     name: Update npm
     command: 'sudo npm install'
  - run:
     name: Install ember globally
     command: 'sudo npm install -g ember-cli'
  - run:
     name: Run ember build
     command: 'sudo npm run build'
  - run:
     name: Deploy app
     command: ./node_modules/.bin/surge dist --domain $SURGE_DOMAIN
  