version: 2
jobs:
 build:
  docker:
   - image: circleci/node:latest
  branches:
      only:
        - master
        - /rc-.*/
  steps:
  - checkout
  - run:
     name: Update npm
     command: 'sudo npm install'
  - run:
     name: Install ember globally
     command: 'sudo npm install -g ember-cli'
  - run:
     name: Run ember build
     command: 'sudo npm run build'
  - run:
     name: Deploy app
     command: './node_modules/.bin/surge dist --domain https://hgnapplication.surge.sh'
  
