version: 2
jobs:
 build_dev:
  docker:
   - image: circleci/node:latest
  steps:
  - checkout
  - run:
     name: Update npm
     command: 'sudo npm install'
  - run:
     name: Install ember globally
     command: 'sudo npm install -g ember-cli'
  - run:
     name: Run ember build
     command: 'sudo APIENDPOINT=$APIENDPOINT_DEV npm run build'
  - run:
     name: Deploy app
     command: ./node_modules/.bin/surge dist --domain $SURGE_DOMAIN_DEV

 build_PROD:
   docker:
   - image: circleci/node:latest
   steps:
    - checkout
    - run:
       name: Update npm
       command: 'sudo npm install'
    - run:
       name: Install ember globally
       command: 'sudo npm install -g ember-cli'
    - run:
       name: Run ember build
       command: 'sudo APIENDPOINT=$APIENDPOINT_PROD npm run build'
    - run:
       name: Deploy app
       command: ./node_modules/.bin/surge dist --domain $SURGE_DOMAIN_PROD
  
workflows:
  version: 2
  deploy:
    jobs:
      - build_dev:
         filters:
            branches:
              ignore: master
      - build_prod:
         filters:
            branches:
              only: master
      

